services:
  postgresql:
    image: bitnami/postgresql:16
    container_name: portfolio_postgres
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=portfolio_api_development
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    restart: unless-stopped

volumes:
  postgresql_data:
    driver: local